### ISSUE TITLE
Needs review

### ISSUE THREAD

**Issue by Milldrew** [Milldrew/accendero-practical#1]
Hello,
@Robert-N7 
@arushirastogi 
@ahoneycutt

Please review my app in production here:
 https://accendero-puhciuothq-uc.a.run.app/newsfeed 

And check the source code in this repo.

if there is anything else you need me to do let me know. I am working full time as an angular SME although I would be happy to build more stuff it helps you.

Thanks!

Andrew Miller
9075900529
 @Milldrew

**Comment by ahoneycutt** [comment]
@Milldrew Hey, thanks for posting up the issue. We are taking a look. One quick note, I'm running docker 20.10 which has built-in `docker compose` support so the `startdb` command needed editing on my end to work. Perhaps something like
```
    "start-db": "cd ./database/ && docker compose > /dev/null && docker compose up -d || docker-compose up -d",
```
would allow switching to whichever `docker-compose` approach the host supports (I do not have `docker-compose` available as a command on my system).

**Comment by Milldrew** [comment]
> @Milldrew Hey, thanks for posting up the issue. We are taking a look. One quick note, I'm running docker 20.10 which has built-in `docker compose` support so the `startdb` command needed editing on my end to work. Perhaps something like
> 
> ```
>     "start-db": "cd ./database/ && docker compose > /dev/null && docker compose up -d || docker-compose up -d",
> ```
> 
> would allow switching to whichever `docker-compose` approach the host supports (I do not have `docker-compose` available as a command on my system).

Awesome solution! Thanks for that! 

On my next iteration I will implement that solution. I am focusing on my current job right now. Let me know if there is anything else I can do.

**Comment by ahoneycutt** [comment]
@Milldrew Thanks for the followup, much appreciated!

**Comment by Milldrew** [comment]
@ahoneycutt closing this issue thanks for your time.

**Comment by ahoneycutt** [comment]
Hey Andrew! Sorry for not responding on the issue. We have an internal review board for applicants. Someone from our operations side will be in touch with you based on our engineering feedback.

Thanks again,
Andy

________________________________

**Comment by Milldrew** [comment]
> Hey Andrew! Sorry for not responding on the issue. We have an internal review board for applicants. Someone from our operations side will be in touch with you based on our engineering feedback. Thanks again, Andy
> […](#)

Thanks! @ahoneycutt

**Comment by Milldrew** [comment]
@Robert-N7 @arushirastogi @ahoneycutt my free tier for GCP ran out! You will receive a 500 error as a result of this https://accendero-puhciuothq-uc.a.run.app/newsfeed.

If you want me to complete another challenge or redeploy this to another free tier please tell me what you need me to do! I think this challenge was really cool!

Thanks!

![Screen Shot 2023-03-20 at 8 06 36 PM](https://user-images.githubusercontent.com/88940946/226502781-12fb2d5b-af0e-45da-98ec-0bd48fc76b7c.png)

**Comment by Milldrew** [comment]
![Screen Shot 2023-03-20 at 8 05 59 PM](https://user-images.githubusercontent.com/88940946/226502716-24cbc803-ec94-4973-bcf3-b794080b1881.png)

**Comment by ahoneycutt** [comment]
Hey Andrew- Thanks for the heads-up! Your code is something we can deploy and test locally :+1: but I appreciate the extra effort here to deploy a live version for us!
________________________________
